### ISSUE TITLE
Third party tool support

### ISSUE THREAD

**Issue by aedsinger** [hello-robot/stretch_urdf#11]
We need a simple way to support 3rd party URDF / tools. The proposed approach is:

* urdf_generate.py moves to stretch_urdf_generate.py
* This tool takes a --path argument to support an arbitrary repository / directory path
* The tool looks under this path for the directory structure matching stretch_urdf
* Then stretch_urdf_generate.py -- path <foo> generates new urdfs using third party mesh and xacro
* Then stretch_urdf_ros_update.py --path <foo> copies the new urdf / xacro / mesh to ROS2 install

**Comment by hello-fazil** [comment]
All the mentioned features have been implemented through `stretch_urdf_ros_update.py` tool. Except the path argument which is tracked in this issue https://github.com/hello-robot/stretch_urdf/issues/25
