### ISSUE TITLE
Remove ground link

### ISSUE THREAD

**Issue by hello-binit** [hello-robot/stretch_urdf#19]
From MF: "The ground link is unnecessary, and creates confusion for users. Instead of having the ground defined as URDF/mesh for collision, we could implement the ground collision detection through a simple condition by checking if the gripper/EOA mesh points go below a certain Z axis threshold."

**Comment by hello-fazil** [comment]
Ground removed link removed in PR https://github.com/hello-robot/stretch_urdf/pull/26
