### ISSUE TITLE
Add the D405 to the TF Tree

### ISSUE THREAD

**Issue by hello-amal** [hello-robot/stretch_urdf#22]
Currently, the D405 is not properly added to the TF tree. There are two core issues:

1. We need to compute the extrinsics transform between `link_gripper_s3_body` --> `gripper_camera_link` and add it to the xacro.
2. In ROS2, [our multi_camera launchfile includes the realsense multi_camera launchfile](https://github.com/hello-robot/stretch_ros2/blob/daa0c74d64e72022c862e92ad623f034ef1fe99a/stretch_core/launch/multi_camera.launch.py#L78), which [adds a default identity transform between the two camera's link frames](https://github.com/IntelRealSense/realsense-ros/blob/1cd6789d0a73ccc4252a9b53ae218309e2ffce87/realsense2_camera/launch/rs_multi_camera_launch.py#L52). So we'll need to copy the realsense_ros logic into our own launchfile and remove the static transform broadcaster.

**Comment by hello-binit** [comment]
Thanks for opening this issue @hello-amal. We'll need to include the "sensor_d405" xacro ([found here](https://github.com/IntelRealSense/realsense-ros/blob/ros2-development/realsense2_description/urdf/_d405.urdf.xacro)) in our [stretch_tool_sg3.xacro](https://github.com/hello-robot/stretch_urdf/blob/main/stretch_urdf/SE3/xacro/stretch_tool_sg3.xacro). This will require computing the extrinsic transform you mentioned in pt 1 from our CAD.

**Comment by hello-fazil** [comment]
p1 and p2 are solved with the following PRs:
- https://github.com/hello-robot/stretch_urdf/pull/23
- https://github.com/hello-robot/stretch_ros2/pull/132
